#!/usr/bin/env bash
#
# Gather the case-study videos into one folder with names that mean something outside this
# repository.
#
# `docs/case-studies/video/onboarding_regression.mp4` is the right name inside the repo and
# the wrong name in a deck, a Drive folder or a message to an investor. This renders
# whatever is missing and copies it out under a numbered, persona-first name, live runs
# first, with an index beside them.
#
# The destination is outside the repository by default. These are demo assets, not source,
# and the live ones are masked recordings of a real CRM -- worth keeping deliberately
# somewhere rather than by accident inside a git tree.
#
# Usage:
#   scripts/collect_demos.sh [destination]     # default: ~/watcher-demos
#
set -euo pipefail

cd "$(dirname "$0")/.."

DEST="${1:-$HOME/watcher-demos}"
VIDEO=docs/case-studies/video

# name|folder|filename  -- filename carries the persona, because that is what a viewer is
# choosing by. Live runs are numbered; the labelled ones keep their dataset name, since
# their whole value is being checkable against a named fixture.
LIVE="
real_pipeline_health|01-founder-is-our-pipeline-real
real_where_deals_die|02-vp-sales-where-deals-die
real_stalled_deals|03-manager-deals-gone-quiet
real_source_quality|04-growth-which-source-actually-closes
real_crm_trust|05-revops-can-i-trust-the-crm
real_hubspot_win_rate|06-anyone-what-is-our-win-rate
"

echo "rendering any missing videos..." >&2
./scripts/make_case_study_videos.sh >/dev/null 2>&1

mkdir -p "$DEST/live-data" "$DEST/labelled-datasets"

index="$DEST/README.md"
{
  echo "# Watcher — demo videos"
  echo
  echo "Generated by \`scripts/collect_demos.sh\`. Re-run it to refresh."
  echo
  echo "## live-data/ — real CRM, every figure and name masked"
  echo
  echo "Recorded against a live HubSpot account. Numbers and customer names are replaced"
  echo "with blocks by \`scripts/mask_cast.py\`, which asserts its own completeness; the"
  echo "reasoning, the citations and the caveats are untouched."
  echo
} > "$index"

for row in $LIVE; do
  name="${row%%|*}"
  friendly="${row##*|}"
  if [ -f "${VIDEO}/${name}.mp4" ]; then
    cp "${VIDEO}/${name}.mp4" "${DEST}/live-data/${friendly}.mp4"
    question=$(head -1 "docs/case-studies/${name}.txt" | sed 's/^Investigating REAL data for tenant [^:]*: //')
    echo "- **${friendly}.mp4** — \"${question}\"" >> "$index"
  fi
done

{
  echo
  echo "## labelled-datasets/ — synthetic data with a known planted cause"
  echo
  echo "Each ends by printing what was actually in the data, so the answer can be marked"
  echo "rather than admired. Nothing is masked because nothing is real."
  echo
} >> "$index"

for cast in docs/case-studies/*.cast; do
  name=$(basename "$cast" .cast)
  case "$name" in real_*) continue ;; esac
  [ -f "${VIDEO}/${name}.mp4" ] || continue
  cp "${VIDEO}/${name}.mp4" "${DEST}/labelled-datasets/${name}.mp4"
  echo "- **${name}.mp4**" >> "$index"
done

{
  echo
  echo "The unedited recordings, and what each one demonstrates, are in the repository at"
  echo "\`docs/case-studies/\`."
} >> "$index"

echo "collected into ${DEST}" >&2
du -sh "$DEST" >&2
