"""Inter-service contracts.

These messages are the service boundary, so the properties worth pinning are the
ones that keep a half-deployed or replayed fleet from producing wrong answers:
tenancy is always explicit, versions are checked rather than guessed, and nothing
but JSON crosses the queue.
"""

from __future__ import annotations

import json
import uuid

import pytest
from pydantic import ValidationError

from cortex.contracts.messages import (
    QUEUE_INGEST,
    QUEUE_INVESTIGATION,
    SCHEMA_VERSION,
    CancelInvestigation,
    InvestigationProgress,
    RunInvestigation,
    SyncConnector,
    SyncResult,
    SyncScope,
    UnsupportedSchemaVersion,
)

ALL_MESSAGES = (
    RunInvestigation,
    CancelInvestigation,
    InvestigationProgress,
    SyncConnector,
    SyncResult,
)


def _minimal(cls: type) -> dict:
    base = {"tenant_id": str(uuid.uuid4())}
    extra: dict[str, object] = {
        RunInvestigation: {"investigation_id": str(uuid.uuid4())},
        CancelInvestigation: {"investigation_id": str(uuid.uuid4())},
        InvestigationProgress: {
            "investigation_id": str(uuid.uuid4()),
            "status": "investigating",
            "step": 3,
        },
        SyncConnector: {"provider": "ga4"},
        SyncResult: {"provider": "ga4", "succeeded": True},
    }[cls]
    return base | extra


class TestTenancyIsAlwaysExplicit:
    @pytest.mark.parametrize("cls", ALL_MESSAGES)
    def test_tenant_id_is_required(self, cls: type) -> None:
        """A worker must never infer tenancy from ambient state."""
        payload = _minimal(cls)
        payload.pop("tenant_id")
        with pytest.raises(ValidationError):
            cls.model_validate(payload)  # type: ignore[attr-defined]

    @pytest.mark.parametrize("cls", ALL_MESSAGES)
    def test_tenant_id_must_be_a_uuid(self, cls: type) -> None:
        payload = _minimal(cls) | {"tenant_id": "acme-corp"}
        with pytest.raises(ValidationError):
            cls.model_validate(payload)  # type: ignore[attr-defined]


class TestVersioning:
    @pytest.mark.parametrize("cls", ALL_MESSAGES)
    def test_defaults_to_current_version(self, cls: type) -> None:
        msg = cls.model_validate(_minimal(cls))  # type: ignore[attr-defined]
        assert msg.schema_version == SCHEMA_VERSION
        msg.require_supported()

    @pytest.mark.parametrize("cls", ALL_MESSAGES)
    @pytest.mark.parametrize("version", [0, 2, 99])
    def test_unknown_version_is_rejected_not_guessed(self, cls: type, version: int) -> None:
        """A half-deployed fleet should fail visibly rather than misinterpret."""
        msg = cls.model_validate(_minimal(cls) | {"schema_version": version})  # type: ignore[attr-defined]
        with pytest.raises(UnsupportedSchemaVersion):
            msg.require_supported()

    def test_error_names_both_versions(self) -> None:
        msg = RunInvestigation.model_validate(_minimal(RunInvestigation) | {"schema_version": 7})
        with pytest.raises(UnsupportedSchemaVersion, match=r"v7.*v1"):
            msg.require_supported()


class TestStrictness:
    @pytest.mark.parametrize("cls", ALL_MESSAGES)
    def test_unknown_fields_are_refused(self, cls: type) -> None:
        """A typo'd field silently ignored is a bug that survives to production."""
        with pytest.raises(ValidationError):
            cls.model_validate(_minimal(cls) | {"tenatn_id": "typo"})  # type: ignore[attr-defined]

    @pytest.mark.parametrize("cls", ALL_MESSAGES)
    def test_messages_are_immutable(self, cls: type) -> None:
        """A consumer mutating a message in flight would desync a retry."""
        msg = cls.model_validate(_minimal(cls))  # type: ignore[attr-defined]
        with pytest.raises(ValidationError):
            msg.tenant_id = uuid.uuid4()

    @pytest.mark.parametrize("cls", ALL_MESSAGES)
    def test_json_roundtrip_is_lossless(self, cls: type) -> None:
        """Only JSON crosses the queue — a pickled payload would let a producer
        execute code inside a worker."""
        msg = cls.model_validate(_minimal(cls))  # type: ignore[attr-defined]
        wire = msg.model_dump(mode="json")
        assert json.loads(json.dumps(wire)) == wire
        assert cls.model_validate(wire) == msg  # type: ignore[attr-defined]


class TestCorrelation:
    @pytest.mark.parametrize("cls", ALL_MESSAGES)
    def test_correlation_id_is_autogenerated(self, cls: type) -> None:
        msg = cls.model_validate(_minimal(cls))  # type: ignore[attr-defined]
        assert isinstance(msg.correlation_id, uuid.UUID)

    def test_correlation_id_survives_a_hop(self) -> None:
        """One investigation must be traceable end to end across services."""
        cid = uuid.uuid4()
        run = RunInvestigation(
            tenant_id=uuid.uuid4(), investigation_id=uuid.uuid4(), correlation_id=cid
        )
        progress = InvestigationProgress(
            tenant_id=run.tenant_id,
            correlation_id=run.correlation_id,
            investigation_id=run.investigation_id,
            status="investigating",
            step=1,
        )
        assert progress.correlation_id == cid

    def test_distinct_messages_get_distinct_ids(self) -> None:
        tid = uuid.uuid4()
        ids = {
            RunInvestigation(tenant_id=tid, investigation_id=uuid.uuid4()).correlation_id
            for _ in range(100)
        }
        assert len(ids) == 100


class TestSyncConnector:
    def test_defaults_to_incremental(self) -> None:
        msg = SyncConnector(tenant_id=uuid.uuid4(), provider="hubspot")
        assert msg.scope is SyncScope.INCREMENTAL
        assert msg.credential_label == "default"

    def test_backfill_is_explicit(self) -> None:
        msg = SyncConnector(tenant_id=uuid.uuid4(), provider="hubspot", scope=SyncScope.BACKFILL)
        assert msg.scope is SyncScope.BACKFILL

    def test_rejects_unknown_scope(self) -> None:
        with pytest.raises(ValidationError):
            SyncConnector(tenant_id=uuid.uuid4(), provider="ga4", scope="everything")  # type: ignore[arg-type]

    def test_window_is_absolute_not_relative(self) -> None:
        """A retry hours later must cover the same window as the original attempt,
        so the contract carries timestamps rather than a duration."""
        fields = set(SyncConnector.model_fields)
        assert {"since", "until"} <= fields
        assert "days" not in fields and "lookback" not in fields


class TestQueueNames:
    def test_queues_are_distinct(self) -> None:
        """Separate queues are what let ingest and investigation scale and fail
        independently."""
        assert QUEUE_INVESTIGATION != QUEUE_INGEST

    def test_queues_are_namespaced(self) -> None:
        for q in (QUEUE_INVESTIGATION, QUEUE_INGEST):
            assert q.startswith("cortex.")
